name: Tender Scraper

on:
  schedule:
    - cron: '0 0,12 * * *'  # 12 AM/PM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Prevent hangs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas urllib3

    - name: Create logs dir
      run: mkdir -p logs

    - name: Run scraper
      run: python -u script.py

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: scraper-logs
        path: logs/
        retention-days: 3
