name: Tender Scraper

on:
  schedule:
    - cron: '0 0,12 * * *'  # Runs at 00:00 (12 AM) and 12:00 (12 PM) every day
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Optional: Also update checkout to v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create logs directory
      run: |
        mkdir -p logs
        sudo chmod 777 logs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas

    - name: Run script with debug
      run: |
        echo "Current working directory: $(pwd)"
        echo "Directory structure before execution:"
        ls -la
        python -u script.py

    - name: Check logs after execution
      run: |
        echo "Directory structure after execution:"
        ls -la
        echo "Logs directory contents:"
        ls -la logs/

    - name: Upload logs as artifact
      if: always()
      uses: actions/upload-artifact@v4  # Critical fix here
      with:
        name: scraper-logs
        path: logs/
